---
# This role will install Controller in group 'controllers' in the environment inventory

- include: docker_login.yml

- name: "pull the {{ docker.image.tag }} image of controller"
  shell: "docker pull {{ docker_registry }}{{ docker.image.prefix }}/controller:{{ docker.image.tag }}"
  when: docker_registry != ""
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"

- name: ensure controller log directory is created with permissions
  file:
    path: "{{ whisk_logs_dir }}/controller{{ groups['controllers'].index(inventory_hostname) }}"
    state: directory
    mode: 0777
  become: true

- name: (re)start controller
  docker_container:
    name: controller{{ groups['controllers'].index(inventory_hostname) }}
    image: "{{ docker_registry }}{{ docker.image.prefix }}/controller:{{ docker.image.tag }}"
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    hostname: "controller{{ groups['controllers'].index(inventory_hostname) }}"
    env:
      "JAVA_OPTS": "-Xmx{{ controller.heap }}"
      "CONTROLLER_OPTS": "{{ controller.arguments }}"
      "CONTROLLER_INSTANCES": "{{ controller.instances }}"

      "COMPONENT_NAME": "controller{{ groups['controllers'].index(inventory_hostname) }}"
      "PORT": 8080

      "WHISK_VERSION_NAME": "{{ whisk_version_name }}"
      "WHISK_VERSION_DATE": "{{ whisk.version.date }}"
      "WHISK_VERSION_BUILDNO": "{{ docker.image.tag }}"

      "KAFKA_HOST": "{{ groups['kafka']|first }}"
      "KAFKA_HOST_PORT": "{{ kafka.port }}"

      "DB_PROTOCOL": "{{ db_protocol }}"
      "DB_PROVIDER": "{{ db_provider }}"
      "DB_HOST": "{{ db_host }}"
      "DB_PORT": "{{ db_port }}"
      "DB_USERNAME": "{{ db_username }}"
      "DB_PASSWORD": "{{ db_password }}"
      "DB_WHISK_ACTIONS": "{{ db.whisk.actions }}"
      "DB_WHISK_AUTHS": "{{ db.whisk.auth }}"
      "DB_WHISK_ACTIVATIONS": "{{ db.whisk.activations }}"

      "LIMITS_ACTIONS_INVOKES_PERMINUTE": "{{ limits.invocationsPerMinute }}"
      "LIMITS_ACTIONS_INVOKES_CONCURRENT": "{{ limits.concurrentInvocations }}"
      "LIMITS_ACTIONS_INVOKES_CONCURRENTINSYSTEM": "{{ limits.concurrentInvocationsSystem }}"
      "LIMITS_TRIGGERS_FIRES_PERMINUTE": "{{ limits.firesPerMinute }}"
      "LIMITS_ACTIONS_SEQUENCE_MAXLENGTH": "{{ limits.sequenceMaxLength }}"
      "LOADBALANCER_INVOKERBUSYTHRESHOLD": "{{ invoker.busyThreshold }}"

      "RUNTIMES_MANIFEST": "{{ runtimesManifest | to_json }}"
    volumes:
      - "{{ whisk_logs_dir }}/controller{{ groups['controllers'].index(inventory_hostname) }}:/logs"
    ports:
      - "{{ controller.basePort + groups['controllers'].index(inventory_hostname) }}:8080"
    command: /bin/sh -c "controller/bin/controller {{ groups['controllers'].index(inventory_hostname) }} >> /logs/controller{{ groups['controllers'].index(inventory_hostname) }}_logs.log 2>&1"

- name: wait until the Controller in this host is up and running
  uri:
    url: "http://{{ ansible_host }}:{{ controller.basePort + groups['controllers'].index(inventory_hostname) }}/ping"
  register: result
  until: result.status == 200
  retries: 12
  delay: 5
