version: "3"

services:
#  zk:
#    image: bobrik/zookeeper
#    network_mode: host
#    environment:
#      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
#      ZK_ID: 1

  master:
    image: mesosphere/mesos-master:1.2.1
    network_mode: host
    pid: host
    userns_mode: host
    privileged: true
#    ports:
#      - "5050:5050"
    environment:
      MESOS_ZK: zk://${DOCKER_IP}:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
#      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: ${DOCKER_IP}
#      MESOS_ADVERTISE_IP: ${DOCKER_IP}
#      LIBPROCESS_IP: ${DOCKER_IP}
#    depends_on:
#      - zk

  slave-one:
    image: mesosphere/mesos-slave:1.2.1
    network_mode: host
    pid: host
    userns_mode: host
    privileged: true
#    ports:
#      - "5051:5051"
    environment:
      MESOS_MASTER: zk://${DOCKER_IP}:2181/mesos
      MESOS_CONTAINERIZERS: docker
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: ${DOCKER_IP}
#      LIBPROCESS_IP: ${DOCKER_IP}
      MESOS_ADVERTISE_IP: ${DOCKER_IP}
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - zk

#   slave-two:
#     image: mesosphere/mesos-slave:1.0.1-2.0.93.ubuntu1404
#     network_mode: host
#     pid: host
#     environment:
#       MESOS_MASTER: zk://127.0.0.1:2181/mesos
#       MESOS_CONTAINERIZERS: docker,mesos
#       MESOS_PORT: 5052
#       MESOS_RESOURCES: ports(*):[12000-12999]
#       MESOS_HOSTNAME: ${DOCKER_IP}
#       LIBPROCESS_IP: ${DOCKER_IP}
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup
#       - /usr/local/bin/docker:/usr/bin/docker
#       - /var/run/docker.sock:/var/run/docker.sock
#     depends_on:
#       - zk

  marathon:
    image: mesosphere/marathon:v1.3.10
    entrypoint:
      - ./bin/start
      - --disable_ha
#    hostname: localhost
    network_mode: host
    pid: host
    userns_mode: host
    privileged: true
    ports:
     - "8080:8080"
#    networks:
#      app_net:
#        ipv4_address: 172.16.121.5
#    links:
#      - zookeeper
#      - mesos-master
    depends_on:
#      - zookeeper
      - master
      - slave-one
    environment:
      - MARATHON_ZK=zk://${DOCKER_IP}:2181/marathon
      - MARATHON_MASTER=zk://${DOCKER_IP}:2181/mesos
      - LIBPROCESS_IP=${DOCKER_IP}